# Provider infra GCP (CAPG, v1.8.x). configSecret pointe vers le Secret
# capi-variables deja cree dans capi-operator-system (GCP_B64ENCODED_CREDENTIALS,
# GCP_PROJECT, etc. selon le format attendu par CAPG). Adapter la version si
# une version differente est deja validee.
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: gcp
  namespace: capi-operator-system
spec:
  version: v1.8.1
  configSecret:
    name: capi-variables
  deployment:
    containers:
      - name: manager
        imageUrl: europe-west1-docker.pkg.dev/k8s-formation/k8s-lab/capg-dns-endpoint@sha256:70fc57efd2e4c1721123ffe56266e6f61c12965c397813d99fc8a2f7395dceb5
