# Control plane GKE (regional autopilot standard). Pas de controlPlaneVersion
# fixe : GKE choisit la version par defaut du releaseChannel "regular".
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedControlPlane
metadata:
  name: cluster-b
  namespace: cluster-b
spec:
  project: k8s-formation
  location: europe-west9
  clusterName: cluster-b
  releaseChannel: regular
