apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedControlPlane
metadata:
  name: cluster-b
  namespace: cluster-b
spec:
  project: k8s-formation
  location: europe-west9-a
  clusterName: cluster-b
  releaseChannel: regular
  controlPlaneAccess:
    dnsAccess: true
    ipAccess: false
  argoCDClusterSecretRef:
    namespace: argocd-greg
    name: argocd-cluster-b
  clusterNetwork:
    useIPAliases: true
    pod:
      cidrBlock: 192.168.0.0/16
